version: "3.8"

# Services
services:
  # Nginx Service
  # http://localhost:8000
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx-PHP
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  # PHP App Service
  app:
    build: ./docker/php
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
    environment:
      DB_NAME: triviaQuiz
      DB_HOST: mysql
      DB_USER: webDev
      DB_PASSWORD: webDev
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: triviaQuiz
      MYSQL_USER: webDev
      MYSQL_PASSWORD: webDev
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
      # or this to have the directory within the project: - ./db_data:/var/lib/mysql

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  # http://localhost:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

# Volumes
volumes:
  db_data:
    driver: local
